baseurl = "https://annlia.github.io/"
title = "A journey through statistics +---+ by Giusi Moffa"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
pluralizeListTitles = false
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[permalinks]
  # setting this means that simple .html files within the folder are not found, 
  # such as jclub.html, but _index.html seems to work instead
  archive = "archive/:year/:month/:day/:slug/"
  projects = "projects/:year/:month/:day/:slug"
  blog = "blog/:year/:month/:day/:slug"

relativeurls = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "This is my attempt at setting up a personal website via github pages, RStudio and Hugo"
  copyright = "&copy;2017 Ann Lia"
  sidebarAbout = [
    "Bookmarks from a statistician",
    "Beware of missing links - this page is work in progress"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "giusi.moffa@unibas.ch"
  
  # Nav links in the side bar
  
  [[params.navlinks]]
  name = "Cicerone"
  url = "about/jabout" 
  
  [[params.navlinks]]
  name = "Academia"
  url = "jacademia/"  
  
  [[params.navlinks]]
  name = "Research"
  url = "jacademia/jresearch"

  [[params.navlinks]]
  name = "Teaching"
  url = "jacademia/jteaching"  
  
  [[params.navlinks]]
  name = "Stats Tea Club"
  url = "jclub/"   
  
  [[params.navlinks]]
  name = "Archive"
  url = "archive/"
  
  [[params.navlinks]]
  name = "Collage"
  url = ""  

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/jcontact"

  [params.social]
  twitter       = "https://twitter.com/giusimoffa"
  linkedin      = "https://www.linkedin.com/in/giusimoffa/"
  github        = "https://github.com/annlia"
  email         = "giusi.moffa@unibas.ch"
  facebook      = "https://www.facebook.com/giusimoffa"
  instagram     = "https://www.instagram.com/giusi.moffa/"
  
# googleplus    = "full profile url in googleplus"  
# stackoverflow = "full profile url in stackoverflow"

  #Adding widgets to the sidebar
  [params.widgets]
    categories = false
    tags = false
    search = false
    
# options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "tomorrow-night-bright"
